package org.donntu.tpr.modes;

public enum CarStatus {
    LOAD_WAITING,
    LOADING,
    MOVING_TO_FIRST_STORE,
    UNLOADING_FIRST,
    MOVING_TO_SECOND_STORE,
    UNLOADING_SECOND,
    MOVING_TO_BAKERY,
    REPAIRING,
    STORE_QUEUE_WAITING


}
